[project]
name = "examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "greyjack>=0.3.9",
    "ortools>=9.15.6755",
]

[tool.uv.sources]
greyjack = { path = "../greyjack", editable = true }

[dependency-groups]
dev = ["pytest>=8,<10"]
